### ISSUE TITLE
IS IT WORKING?

### ISSUE THREAD

**Issue by ysharoiko** [takeflight/wagtailnews#12]
I was trying wagtailnews.

I Added 

# The decorator registers this model as a news index
@newsindex
class NewsIndex(NewsIndexMixin, Page):
    # Add extra fields here, as in a normal Wagtail Page class, if required
    newsitem_model = 'NewsItem'

class NewsItem(AbstractNewsItem):
    # NewsItem is a normal Django model, *not* a Wagtail Page.
    # Add any fields required for your page.
    # It already has ``date`` field, and a link to its parent ``NewsIndex`` Page
    title = models.CharField(max_length=255)
    body = RichTextField()

    panels = [
        FieldPanel('title', classname='full title'),
        FieldPanel('body', classname='full'),
    ] + AbstractNewsItem.panels

    def __str__(self):
        return self.title

Into home/modes.py

And was able to add new NEWS INDEX element. But when i try to see that page i get error
Looks like no templates are available, but they are installed in Env/lib/python3.5/site-packages/wagtailnews/templates 
What is wrong with it?

Request Method: | GET
-- | --
http://localhost:8000/w/
1.11.8
TemplateDoesNotExist
home/news_index_all.html, home/news_index.html
/home/user/Env/bl_test/lib/python3.5/site-packages/django/template/loader.py in select_template, line 53
/home/user/Env/bl_test/bin/python
3.5.2
['/home/user/django_wagtail/ntest',  '/home/user/Env/bl_test/lib/python35.zip',  '/home/user/Env/bl_test/lib/python3.5',  '/home/user/Env/bl_test/lib/python3.5/plat-x86_64-linux-gnu',  '/home/user/Env/bl_test/lib/python3.5/lib-dynload',  '/usr/lib/python3.5',  '/usr/lib/python3.5/plat-x86_64-linux-gnu',  '/home/user/Env/bl_test/lib/python3.5/site-packages']
Чт, 7 Дек 2017 17:06:36 +0000

**Comment by seb-b** [comment]
You'll need to add your own templates for the NewsIndex and NewsItems same as you would for other wagtail pages, the templates included in Wagtailnews are for the admin only.

There's some info [here](https://docs.djangoproject.com/en/2.0/topics/templates/) about where Django looks for templates
