### ISSUE TITLE
Extending behavior of news item workflow isn't as convenient as other wagtail workflow

### ISSUE THREAD

**Issue by Taywee** [takeflight/wagtailnews#9]
If I want to do something universally on a "publish" action of a news item, for instance, it's not as easy as it should be.  I can override the "publish" method on the revision, but that unfortunately only gets called on an edit, not on a creation publish.

I suggest either custom django signals sent out at various points or custom hooks through wagtail's hook system.  I'd be happy to do this work and make a pull request.  At a baseline, signals/hooks should be supported for news item publishing (ideally with some kwarg or something indicating whether it's an edit or a new creation) and unpublishing, as well as deletion and draft-saving.

**Comment by seb-b** [comment]
Good idea, a pull request would be welcome :smile: . I believe wagtail uses signals for it's page event actions so it would be nice to be consistent with that.
